### ISSUE TITLE
Sending IPC message to main.js on menu item click

### ISSUE THREAD

**Issue by Quenos** [saisandeepvaddi/electron-custom-menu-bar#1]
Sorry to bother you this way, but I am trying to send  an IPC message to main.js when a menu item is clicked.
I've adapted your code menu.js:

```
const template = [
  {
    label: "Accounting",
    submenu: [
      { label: "Send message",
        click: () => {
         const { ipcRenderer } = require('electron');
          ipcRenderer.send('test', 'Hallo');
      }},
      { label: "Do something else" }],
  },
  // { role: 'editMenu' }
...
```

But this gives an error saying unknown doesn't have a function send.

Can you help? Thank you.

<img width="424" alt="Screenshot 2020-06-30 at 14 41 39" src="https://user-images.githubusercontent.com/34926461/86127237-da3b1580-badf-11ea-95c1-483c98858038.png">

Some side note: What I'm actually try to accomplish is to load another HTML file into the main window. So I want to send a message to the main window, which will then load a new HTML file with different functionality.

**Comment by saisandeepvaddi** [comment]
Menu is accessed from main process. `ipcRenderer` works only in renderer process. 
That means, `ipcRenderer` can only be used in your UI code.
If you want to send a message to renderer of a `BrowserWindow`, you should use something like ,
```js
{
label: "Send message",
click(menuItem, browserWindow, event) {
   browserWindow.webContents.send("test", "Hallo");
}
```
You can listen to this event in your JS in your renderer (JS in your UI) with something like
```js
const {ipcRenderer} = require("electron");
ipcRenderer.on("test", (event, args ) => {console.log(args);})
```

You mentioned in your sidenote that you want to load another HTML on clicking this menu item. I don't think you need an RPC call for that. Try doing,
```js
{
label: "Send message",
click(menuItem, browserWindow, event) {
   browserWindow.loadFile("path to html");
}
```

**Comment by Quenos** [comment]
Thanks Sai,

The loadFile solution did I exactly what I wanted!
